spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
  show-sql: true
  properties.hibernate.format_sql: true


spring:
  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:postgresql://c5p86clmevrg5s.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/dca4jdb147a940
    username: ua6o9vbkovpag5
    password: p7486f9db81b4a92d95e3ea26a60b1ec177557295620ddf4beae5558d6547212e
    platform: postgres
    driver-class-name: org.postgresql.Driver
  redis:
    url: redis://:pf3d56dbb83c57fb0883292c4b3c2251a97b573be0c1f4d0af0f983fb28d3cf45@ec2-52-202-64-25.compute-1.amazonaws.com:10949


jwt:
  secret-key: fast_campus.sns-application-2024.secret_key
  token.expired-time-ms: 2592000000 # 30 days